<script src="../vendors/js/vendor.bundle.base.js"></script>
<script src="../vendors/chart.js/Chart.min.js"></script>
<script src="../vendors/js/off-canvas.js"></script>
<script src="../vendors/js/hoverable-collapse.js"></script>
<script src="../vendors/js/template.js"></script>
<script src="../vendors/js/dashboard.js "></script>
<script src="../vendors/js/file-upload.js"></script>
<script src="../vendors/js/jquery-3.6.0.min.js"></script>
<script src="../includes/search.js"></script>
